name: neuray_gen6d

# network
network: neuray_gen6d
init_net_type: dino
use_hierarchical_sampling: true
use_depth_loss: true
dist_decoder_cfg:
  use_vis: false

# loss
loss: [render, depth]
val_metric: [psnr_ssim, vis_img]
key_metric_name: psnr_nr_fine
use_dr_loss: false
use_dr_fine_loss: false
use_nr_fine_loss: true
depth_correct_ratio: 1.0

# lr
total_step: 400000
val_interval: 1
lr_type: exp_decay
lr_cfg:
  lr_init: 4.0e-4
  decay_step: 100000
  decay_rate: 0.5


# dataset
train_dataset_type: gen
train_dataset_cfg:
  resolution_type: hr
  type2sample_weights: {gso: 80, dtu_train: 20, real_iconic: 10, space: 20, real_estate: 40}
  train_database_types: ['dtu_train','space','real_iconic','real_estate','gso']
  aug_pixel_center_sample: true
  ref_pad_interval: 32
  use_src_imgs: true

val_set_list:
  -
    name: linemod
    type: gen
    cfg:
      val_database_name: example/custom/480
      use_src_imgs: true